# Generated by Django 5.1.15 on 2026-05-31 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_extras_grupo_config'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(blank=True, default='', max_length=200)),
                ('tipo_calculo', models.CharField(blank=True, default='', max_length=30)),
                ('descripcion', models.CharField(blank=True, default='', max_length=500)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva_pct', models.DecimalField(decimal_places=2, default=16, max_digits=5)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ganancia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('margen', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizacion_items', to='productos.categoria')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.cotizacion')),
            ],
            options={
                'verbose_name': 'Ítem de cotización',
                'verbose_name_plural': 'Ítems de cotización',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['cotizacion'], name='ventas_coti_cotizac_0b1b93_idx')],
            },
        ),
    ]
