# Generated by Django 5.1.15 on 2026-06-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_cotizacionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estatus',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('proximo', 'Próximo'), ('urgente', 'Urgente'), ('en_produccion', 'En Producción'), ('listo', 'Listo'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
