# Generated by Django 5.1.15 on 2026-05-31 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_objetivo', models.DecimalField(decimal_places=2, default=230, max_digits=8)),
                ('hora_laser', models.DecimalField(decimal_places=2, default=30, max_digits=8)),
                ('meta_mensual', models.DecimalField(decimal_places=2, default=20000, max_digits=10)),
            ],
            options={
                'verbose_name': 'Configuración del sistema',
                'verbose_name_plural': 'Configuración del sistema',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_calculo', models.CharField(choices=[('precio_fijo', 'Precio fijo + opciones'), ('por_dimension', 'Por dimensión'), ('tabla_tiered', 'Tabla de precios por niveles'), ('por_hora', 'Por horas de trabajo'), ('manual', 'Entrada manual')], max_length=30)),
                ('categoria_display', models.CharField(max_length=100)),
                ('icono', models.CharField(default='📦', max_length=10)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['orden', 'nombre'],
                'indexes': [models.Index(fields=['activo'], name='productos_p_activo_31f808_idx'), models.Index(fields=['tipo_calculo'], name='productos_p_tipo_ca_ef4b27_idx'), models.Index(fields=['categoria_display'], name='productos_p_categor_641fae_idx')],
            },
        ),
    ]
