# Generated by Django 5.1.15 on 2026-05-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_migrate_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo_calculo',
            field=models.CharField(choices=[('precio_fijo', 'Precio fijo + opciones'), ('por_dimension', 'Por dimensión'), ('tabla_tiered', 'Tabla de precios por niveles'), ('por_hora', 'Por horas de trabajo'), ('manual', 'Entrada manual')], default='precio_fijo', max_length=30),
        ),
    ]
